### PR TITLE
scrape mirrorlist for closest

### PR DESCRIPTION
**Pull request by philclifford**
~~I haven't tested this but it is a start.~~ 
Now tested and working.

### CODE REVIEW

**Comment by philclifford** [comment]
sorry for all the fat-finger behaviour.  Hopefully no more weird middle-button pastes while typing too quickly for a friday night ;-)

**Comment by philclifford** [comment]
got there in the end :smile:

**Comment by daPhipz** [comment]
Thanks for your contribution! I decided to merge our work in one co-authored commit instead of merging your branch - looks cleaner imo.
This really helped me understand string manipulation and piping, thanks again :)

**Comment by philclifford** [comment]
Glad it helped. Always happy to learn together.

**Pull request closed without merging**
